
target:
    image: data/cal/cam1.tif 
    number: 0
    ori_file: config/cal/cam1.tif.ori
    addpar_file: config/cal/cam1.tif.addpar
    known_points: config/cal/points1.txt
    manual_detection_points: [ 23, 27, 29, 33 ]
    manual_detection_file: config/cal/cam1_man.txt
    glass_vec: [ 0., 0., 118. ]

scene:
    flags: hp, headers
    image_size: [ 1280, 1024 ]
    pixel_size: [ 0.014, 0.014 ]
    
    # Multimedia parameters:
    cam_side_n: 1  # air
    object_side_n: 1.335  # water
    wall_ns: [ 1.43 ] # perspex
    wall_thicks: [ 5 ]

detection:
    discont: 500
    gvthresh: [10, 10, 10, 10]
    pixel_count_bounds: [100, 2000]
    xsize_bounds: [10, 100]
    ysize_bounds: [10, 100]
    min_sum_grey: 200
    cross_size: 2

default_free_vars: [ cc ]

